### ISSUE TITLE
error when run horse2zebra dataset

### ISSUE THREAD

**Issue by zsdonghao** [tensorlayer/cyclegan#1]
Traceback (most recent call last):
  File "train.py", line 97, in <module>
    for i, batch in enumerate(dataloader):
  File "/home/asus/Workspace/envtf2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/asus/Workspace/envtf2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/asus/Workspace/envtf2/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 6.
Original Traceback (most recent call last):
  File "/home/asus/Workspace/envtf2/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/asus/Workspace/envtf2/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/asus/Workspace/envtf2/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/asus/Workspace/PyTorch-CycleGAN/datasets.py", line 21, in __getitem__
    item_B = self.transform(Image.open(self.files_B[random.randint(0, len(self.files_B) - 1)]))
  File "/home/asus/Workspace/envtf2/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/home/asus/Workspace/envtf2/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 166, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/asus/Workspace/envtf2/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 217, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256]

**Comment by TavRotenberg** [comment]
hi, I got the same error. how did you fix it?

**Comment by zsdonghao** [comment]
check your data, make sure they are all 3 channels

**Comment by TavRotenberg** [comment]
thanks! I've checked it by running:
img = cv2.imread(img_path)
and checking that:
len(img.shape) == 3
and all images have the shape of 3.
Is that enough? or should I check  something else?
